rendering: ~
security:
  class: afsStudioBasicSecurityFilter
  
csrf:
  enabled: false
  
cache:     ~
common:    ~

parser_validation: 
  class: XmlParserValidationFilter

null_filter: ~

exception_catching: ~

execution: ~