admin:
  first_name: Admin
  last_name: Admin
  email: admin@appflower.com
  password: d033e22ae348aeb5660fc2140aec35850c4da997
  role: admin
user:
  first_name: 'User First Name'
  last_name: 'User Last Name'
  email: startsev.sergey@gmail.com
  password: d99ef6000c8bd64dbc971f7dacaf1752585386ef
  role: user
